name: Submit Slurm Job to PARAM

on:
  push:
    branches:
      - test-hello
    paths:
      - '**.py'

jobs:
  run-on-param:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Submit to SLURM
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          JOBNAME="job_${TIMESTAMP}"
          LOGDIR="/home/sarthaks/InternWork/logs"
          SCRIPT="${GITHUB_WORKSPACE}/hello.py"

          echo "#!/bin/bash" > job.sh
          echo "#SBATCH -N 1" >> job.sh
          echo "#SBATCH --ntasks-per-node=1" >> job.sh
          echo "#SBATCH --time=00:05:00" >> job.sh
          echo "#SBATCH --job-name=${JOBNAME}" >> job.sh
          echo "#SBATCH --output=${LOGDIR}/${JOBNAME}.out" >> job.sh
          echo "#SBATCH --error=${LOGDIR}/${JOBNAME}.err" >> job.sh
          echo "#SBATCH --partition=standard" >> job.sh

          echo "cd ${GITHUB_WORKSPACE}" >> job.sh
          echo "source /home/sarthaks/miniconda3/etc/profile.d/conda.sh" >> job.sh
          echo "conda activate mor_env" >> job.sh
          echo "python ${SCRIPT}" >> job.sh

          JOB_ID=$(sbatch --parsable job.sh)

          echo "Waiting for Slurm job ${JOB_ID} to finish..."
          while squeue -j "$JOB_ID" 2>/dev/null | grep -q "$JOB_ID"; do
            sleep 5
          done
          echo "Slurm job ${JOB_ID} completed."
          
      - name: Push Output File to GitHub
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          cd ${GITHUB_WORKSPACE}

          git config user.name "PARAM Runner Bot"
          git config user.email "runner@company.com"

          git add outputs/testHelloOutput.txt job.sh

          if git diff --cached --quiet; then
            echo "🟡 Nothing new to commit"
          else
            git commit -m "Add pipeline output for intern"
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/sarthaksam003/ReasoningLLM.git
            git push origin HEAD:test-hello
          fi
